version: "3.8"

services:
  client:
    image: client:dev_v1
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8900:80"
    restart: always
    depends_on:
      - product-service
      - user-service
      - cart-service
    networks:
      - app-network

  user-service:
    image: user-service:dev_v1
    build:
      context: ./User
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - PORT_USER_SERVICE=${PORT_USER_SERVICE}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      # - MONGO_USERNAME=${MONGO_USERNAME}
      # - MONGO_PASSWORD=${MONGO_PASSWORD}
      # - MONGO_CLUSTER=${MONGO_CLUSTER}
    restart: always
    ports:
      - "${PORT_USER_SERVICE}:${PORT_USER_SERVICE}"
    depends_on:
      - db
    networks:
      - db-network
      - app-network

  cart-service:
    image: cart-service:dev_v1
    build:
      context: ./Cart
      dockerfile: Dockerfile
    restart: always
    container_name: cart-service
    environment:
      - PORT_CART_SERVICE=${PORT_CART_SERVICE}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      # - MONGO_USERNAME=${MONGO_USERNAME}
      # - MONGO_PASSWORD=${MONGO_PASSWORD}
      # - MONGO_CLUSTER=${MONGO_CLUSTER}
    ports:
      - "${PORT_CART_SERVICE}:${PORT_CART_SERVICE}"
    depends_on:
      - db
    networks:
      - db-network
      - app-network

  product-service:
    image: product-service:dev_v1
    build:
      context: ./Product
      dockerfile: Dockerfile
    restart: always
    container_name: product-service
    environment:
      - PORT_PRODUCT_SERVICE=${PORT_PRODUCT_SERVICE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      # - MONGO_USERNAME=${MONGO_USERNAME}
      # - MONGO_PASSWORD=${MONGO_PASSWORD}
      # - MONGO_CLUSTER=${MONGO_CLUSTER}
    ports:
      - "${PORT_PRODUCT_SERVICE}:${PORT_PRODUCT_SERVICE}"
    depends_on:
      - db
    networks:
      - db-network
      - app-network

  db:
    image: mongo:4.4
    volumes:
      - ./.docker/data/db:/data/db
    restart: unless-stopped
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
    name: db-network
  app-network:
    driver: bridge
    name: app-network
